# config-repo/auth-service.yml
spring:
  datasource:
    url: jdbc:mysql://mysql-user-master:3307/quizcard_db_user
    username: admin
    password: adminpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  cache:
    type: redis
  redis:
    host: redis-cache-1
    port: 6380

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/