# config-repo/collection-service.yml
spring:
  datasource:
    url: jdbc:mysql://mysql-set-card-master:3310/quizcard_db_set_card
    username: admin
    password: adminpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  cache:
    type: redis
  redis:
    host: redis-cache-2
    port: 6381

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/